// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmppxuqvmhtnvjdgilja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtcHB4dXF2bWh0bnZqZGdpbGphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNDM0NDEsImV4cCI6MjA1OTYxOTQ0MX0.KrKw_Ra-FsymQyurQSBzW_OCUjkt33nAR75WCqhfvZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);